stages:
  - setup


setup_scanoss:
  stage: setup
  image: python:3.9
  script:
    - echo "Updating environment..."
    - apt-get update && apt-get install -y python3 python3-pip
    - echo "Installing SCANOSS CLI globally..."
    - pip install --upgrade scanoss  # Install SCANOSS globally
    - echo "Verifying SCANOSS installation..."
    - which scanoss-py || echo "scanoss-py not found!"
    - scanoss-py --version || echo "SCANOSS CLI not installed correctly!"
    - scanoss-py scan . > output.spdx
    - cat output.spdx

  artifacts:
    paths:
    - output.spdx
