name: SCANOSS Scan

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install SCANOSS CLI
        run: |
          pip install --upgrade scanoss

      - name: Verify SCANOSS installation
        run: |
          scanoss-py --version

      - name: Run SCANOSS scan
        run: |
          scanoss-py scan . > output.spdx
          cat output.spdx

      - name: Upload SCANOSS report
        uses: actions/upload-artifact@v3
        with:
          name: scanoss-report
          path: output.spdx
