name: SCANOSS Scan

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SCANOSS CLI
        run: |
          curl -sSL https://scanoss.com/install.sh | bash
          echo "$HOME/.scanoss/bin" >> $GITHUB_PATH

      - name: Run SCANOSS scan
        run: scanoss scan . --output scanoss_report.spdx.json
